name: Bug Report
description: Report a bug or issue with a command
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please fill out the form below.

  - type: input
    id: command
    attributes:
      label: Command
      description: Which command has the issue?
      placeholder: "/r-check"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the issue
      placeholder: Tell us what went wrong
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?

  - type: input
    id: gemini-version
    attributes:
      label: Gemini CLI Version
      placeholder: "1.0.0"

  - type: input
    id: r-version
    attributes:
      label: R Version
      placeholder: "4.4.0"
