name: Feature Request
description: Suggest a new command or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! Please describe your idea.

  - type: dropdown
    id: type
    attributes:
      label: Request Type
      options:
        - New command
        - Improve existing command
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like?
      placeholder: Describe your idea
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: When would this be helpful?
      placeholder: Describe a scenario

  - type: input
    id: related-command
    attributes:
      label: Related Command
      description: Is this related to an existing command?
      placeholder: "/r-check"
